[package]
name = "pjsekai_thumbnail_matcher_web"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pjsekai_thumbnail_matcher = { path = "../lib" }

dioxus = "0.3"
dioxus-web = "0.3"
